---
version: 2

registries:
  github-private:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.PRIVATE_REPO_TOKEN }}

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    groups:
      patch-minor-action-updates:
        update-types:
          - patch
          - minor
  - package-ecosystem: docker
    directory: .devcontainer
    schedule:
      interval: daily
    commit-message:
      prefix: build
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    registries:
      - github-private
