ENABLE:
  - ACTION
  - CPP
  - DOCKERFILE
  - JSON
  - MARKDOWN
  - SPELL
  - XML
  - YAML
DISABLE_LINTERS:
  - ACTION_ZIZMOR
  - CPP_CPPLINT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
  - SPELL_CSPELL
  - JSON_V8R
  - REPOSITORY_SYFT
  - YAML_V8R
DISABLE_ERRORS_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SPELL_LYCHEE
PRINT_ALPACA: false
SARIF_REPORTER: true
SHOW_SKIPPED_LINTERS: false
JSON_JSONLINT_ARGUMENTS: --mode cjson
CPP_CPPCHECK_ARGUMENTS: --suppress=normalCheckLevelMaxBranches --library=qt
